import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";
import styles from "../styles/main.module.css";
import { IconBrandInstagram, IconBrandDiscord } from "@tabler/icons-react";

const myFont = localFont({ src: "../../public/fonts/FleuronRegular.otf" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={myFont.className}>
			<body>
				<nav className={styles.navbar}>
					<a href="/" className={styles.navbar_link}>
						Home
					</a>
					<Image src="/imgs/logo.webp" alt="logo" width={250} height={250} />
					<a href="/showcase" className={styles.navbar_link}>
						Showcase
					</a>
				</nav>
				{children}
				<footer className={styles.footer}>
					<a href="#" className={styles.footer_link}>
						<IconBrandInstagram
							stroke={2}
							className={styles.footer_link_icon}
						/>
					</a>
					<a href="#" className={styles.footer_link}>
						<IconBrandDiscord stroke={2} />
					</a>
					<a href="#" className={styles.footer_link}>
						RAFFLE
					</a>
					<a href="#" className={styles.footer_link}>
						PRIVACY
					</a>
					<a href="#" className={styles.footer_link}>
						TERMS & CONDITIONS
					</a>
				</footer>
			</body>
		</html>
	);
}
