import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";
import styles from "../styles/navbar.module.css";

const myFont = localFont({ src: "../../public/fonts/FleuronRegular.otf" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={myFont.className}>
			<body>
				<nav className={styles.navbar}>
					<a href="/">Home</a>
					<Image src="/imgs/logo.webp" alt="logo" width={300} height={300} />
					<a href="/">Showcase</a>
				</nav>
				{children}
				<footer></footer>
			</body>
		</html>
	);
}
